function v = func_v_hypothrochoid(t,T,n,hstart,hend,wstart,wend)
%FUNC_V_HYPOTHROCHOID
%    V = FUNC_V_HYPOTHROCHOID(T,T,N,HSTART,HEND,WSTART,WEND)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Feb-2017 15:33:03

t2 = n+1.0;
t3 = 1.0./t2;
t4 = n-1.0;
t6 = hend.*n.*t3.*2.0;
t7 = hend.*t3.*t4;
t5 = t6-t7;
t8 = 1.0./t4;
t9 = t.*wend;
t10 = 1.0./hend;
t11 = t.*t2.*t5.*t8.*t10.*wend;
v = [-t5.*wend.*sin(t9)-t2.*t5.*t8.*wend.*sin(t11);t5.*wend.*cos(t9)-t2.*t5.*t8.*wend.*cos(t11)];
