function Q = func_eqs_IK_all(pEx,pEy,Lf,Lu,Lb)
%FUNC_EQS_IK_ALL
%    Q = FUNC_EQS_IK_ALL(PEX,PEY,LF,LU,LB)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Dec-2016 13:36:14

t2 = Lb.*(1.0./2.0);
t3 = pEx-t2;
t4 = pEx-t2;
t5 = pEy.^2;
t6 = pEy.*1i;
t7 = -pEx+t2+t6;
t8 = angle(t7);
t9 = 1.0./Lu;
t10 = pEx-t2;
t11 = pEx-t2;
t12 = Lf.^2;
t13 = Lu.^2;
t14 = pEx-t2;
t15 = pEx-t2;
t16 = pEx-t2;
t17 = pEx-t2;
t18 = Lb.*5.0e-1i;
t19 = pEx+t2;
t20 = t19.^2;
t21 = t5+t20;
t22 = 1.0./sqrt(t21);
t23 = t5-t12+t13+t20;
t24 = t9.*t22.*t23.*(1.0./2.0);
t25 = acos(t24);
t26 = pEx+t2+t6;
t27 = angle(t26);
t28 = t25+t27;
t35 = pEx.*1i;
t29 = -t35;
t30 = pEx-t2;
t31 = pEx-t2;
t32 = pEx-t2;
t33 = pEx-t2;
t34 = pi.*(3.0./2.0);
t36 = cos(t28);
t37 = Lu.*t36.*-1i;
t38 = sin(t28);
Q = [-t8+pi-acos(t9.*1.0./sqrt(t5+t3.^2).*(t5-t12+t13+t4.^2).*(1.0./2.0));-t8+t34-acos(t9.*1.0./sqrt(t5+t10.^2).*(t5-t12+t13+t11.^2).*(1.0./2.0))-angle(pEy+t18+t29-Lu.*cos(t8+acos(t9.*1.0./sqrt(t5+t14.^2).*(t5-t12+t13+t15.^2).*(1.0./2.0))).*1i-Lu.*sin(t8+acos(t9.*1.0./sqrt(t5+t16.^2).*(t5-t12+t13+t17.^2).*(1.0./2.0))));angle(pEx.*1i+pEy+t18+t37-Lu.*t38)+angle(pEy+t18+t29-Lu.*cos(t8+acos(t9.*1.0./sqrt(t5+t30.^2).*(t5-t12+t13+t31.^2).*(1.0./2.0))).*1i-Lu.*sin(t8+acos(t9.*1.0./sqrt(t5+t32.^2).*(t5-t12+t13+t33.^2).*(1.0./2.0))));-t25-t27+t34-angle(pEy+t18+t35+t37-Lu.*t38);t28];
