function Q = func_eq_IK(pEx,pEy,Lf,Lu,Lb)
%FUNC_EQ_IK
%    Q = FUNC_EQ_IK(PEX,PEY,LF,LU,LB)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Dec-2016 13:36:14

t2 = Lb.*(1.0./2.0);
t3 = pEx-t2;
t4 = pEx-t2;
t5 = pEy.^2;
t6 = 1.0./Lu;
t7 = pEx+t2;
t8 = Lf.^2;
t9 = Lu.^2;
t10 = t7.^2;
t11 = pEy.*1i;
Q = [pi-acos(t6.*1.0./sqrt(t5+t3.^2).*(t5-t8+t9+t4.^2).*(1.0./2.0))-angle(-pEx+t2+t11);angle(pEx+t2+t11)+acos(t6.*1.0./sqrt(t5+t10).*(t5-t8+t9+t10).*(1.0./2.0))];
