function p = func_p_hypothrochoid(t,T,n,hstart,hend,wstart,wend)
%FUNC_P_HYPOTHROCHOID
%    P = FUNC_P_HYPOTHROCHOID(T,T,N,HSTART,HEND,WSTART,WEND)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Feb-2017 15:33:03

t2 = n+1.0;
t3 = 1.0./t2;
t4 = n-1.0;
t7 = hend.*n.*t3.*2.0;
t8 = hend.*t3.*t4;
t5 = t7-t8;
t6 = t.*wend;
t9 = 1.0./hend;
t10 = 1.0./t4;
t11 = t.*t2.*t5.*t9.*t10.*wend;
p = [hend.*cos(t11)+t5.*cos(t6);-hend.*sin(t11)+t5.*sin(t6)];
